greenbone/greenbone-feed-sync

README.md

Update README for adding usage and settings summary
In nearly 99% of all cases users should not tweak their settings and just run `greenbone-feed-sync`.
DEVOPS-510

Change: Update README for adding usage and settings summary

---

README.md
greenbone/feed/sync/parser.py
greenbone/feed/sync/rsync.py
tests/test_parser.py
tests/test_rsync.py

Allow to set a timeout for rsync
Add a new rsync-timeout setting to allow to change the rsync timeout behavior. By default rsync should wait forever which is the same as using 0 as timeout value.

Add: Allow to set a timeout for rsync

---

greenbone/feed/sync/helper.py

Ensure the lock file is read and writable by the users group
When creating a lock file for a feed ensure that the group can read and write the lock file. This change ensure that the same permissions are applied as with gvmd, ospd-openvas and the old sync scripts.

Change: Ensure the lock file is read and writable by the users group

---

.github/workflows/release-pontos.yml

Use standard release action
Use our standard release action as the Python one is deprecated.
DEVOPS-539

Change: Use standard release action

---

README.md
greenbone/feed/sync/helper.py
greenbone/feed/sync/main.py
greenbone/feed/sync/parser.py
tests/test_helper.py
tests/test_main.py
tests/test_parser.py

When running as root switch to different user and group
Instead of forbid running as root, switch to a different effective user and group that both can be configured. By default user and group name are `gvm`. This allows running `greenbone-feed-sync` via a superuser tool like `sudo` or `gosu` without having to remember the special user it needs to run with.

Add: When running as root switch to different user and group

---

greenbone/feed/sync/helper.py

Fix changing the group when running as root
When changing the effective group and user of the current process the group id must be changed before the user id because otherwise it wont be possible to change the group anymore.

Fix: Fix changing the group when running as root

---

.github/workflows/release-pontos.yml

Use workflow_dispatch branch for release
Don't require an input for the to be released branch. Just use the branch of the selected workflow.
Easier release workflow.
DEVOPS-547

Change: Use workflow_dispatch branch for release

---

README.md

Update README for lock file defaults
Mixed up the default values for the openvas and gvmd lock files in the README.

Fix: Update README for lock file defaults

---

greenbone/feed/sync/main.py
greenbone/feed/sync/parser.py
tests/test_main.py
tests/test_parser.py

Add: selftest command line option.
Since this script replace the `greenbone-nvt-sync`, it must provide at least the option which are still required by other modules Ospd-openvas calls it with `--selftest` and sent this information to gvmd. The GMP related command is `<get_feeds/>`

Add: selftest command line option.

---

greenbone/feed/sync/main.py
tests/test_main.py

Always run selftest
Refactor selftest to raise exception instead of using C-style return values. Using exceptions allows for CLI output in the caller and makes the function independent of a user interface.
Also do the selftest on every run to give the user feedback about missing but required applications.

Change: Always run selftest

---

greenbone/feed/sync/main.py
tests/test_main.py

Drop check for sha256sum in selftest
The application sha256sum is not used in the greenbone-feed-sync script. The script should only check for things it actually uses.

Remove: Drop check for sha256sum in selftest

---

README.md

Update readme to document installation via pipx
With newest distros the externally-managed flag is considered and pip doesn't allow to install python packages without virtual environments anymore (see [PEP 668](https://peps.python.org/pep-0668)).
Therefore add a section about installing via pipx.

Add: Update readme to document installation via pipx

---

.github/dependabot.yml

Update dependabot config to create commits which use conventional commit message
Include dependency updates in release changelogs

Add: Include dependency updates in release changelogs

---

README.md

Fix README for installation with pipx
Fix copy and paste mistake for chapter about using pipx for installing greenbon-feed-sync. Also add some more improvements like using sudo for apt install.

Fix README for installation with pipx

---

README.md

Update README to use sudo and add a chapter about running greenbone-feed-sync on Kali Linux. 
`greenbone-feed-sync` should be run via sudo to ensure the correct permissions are used. Kali uses a different user and group then our community docs.

Update README for running on Kali Linux

---

greenbone/feed/sync/helper.py
tests/test_helper.py

Check if user and group exists when running as sudo
Create helpful error message when running as root and trying to switch to an non existing user or group.

Check if user and group exists when running as sudo

---

greenbone/feed/sync/main.py
tests/test_main.py

Make errors more visible in the terminal
Don't let errors look like normal terminal output. Instead highlight the error.

Make errors more visible in the terminal

---

.docker/Dockerfile
.docker/entrypoint.sh
.dockerignore
.github/workflows/container.yml

Publish container image for greenbone-feed-sync
Build and upload a container image for greenbone-feed-sync to hub.docker.com.
Part 1 to fix https://github.com/greenbone/docs/issues/367

Add: Publish container image for greenbone-feed-sync

---

greenbone/feed/sync/config.py
tests/test_config.py
tests/test_main.py
tests/test_parser.py

Replace hardcoded version number with a constant.
Prevent duplicated values in strings.
None.

refactor: Replace hardcoded version number with a constant

---

.github/workflows/deploy-pypi.yml

Use trusted publisher upload for PyPI
[Trusted publisher](https://docs.pypi.org/trusted-publishers/) improves the security of the deployment
DEVOPS-940

 Change: Use trusted publisher upload for PyPI

---

README.md
greenbone/feed/sync/parser.py
poetry.lock
pyproject.toml

Add bash and zsh completion for greenbone-feed-sync
Allow to install command completions for bash and zsh. This improves the usability of the tool a lot.

Add: Add bash and zsh completion for greenbone-feed-sync

---

greenbone/feed/sync/helper.py
tests/test_helper.py

Handle error for missing permission on lock file
Raise a FileLockingError when the lock file can't be opened due to missing permissions. This will display a better error message and not a full Python traceback.
https://forum.greenbone.net/t/feed-sync-all-falling/17085

Change: Handle error for missing permission on lock file

---

.docker/Dockerfile

Install ssh-client package in the container image to allow rsync via ssh.
This fixes rsync is failing because of missing ssh client. "rsync: [Receiver] Failed to exec ssh: No such file or directory (2)" This fails only while using enterprise feed

Added ssh client

---

.github/workflows/ci-python.yml

Fix: Use ruff check as linter
Using `ruff` is deprecated ...
[DEVOPS-1093](https://jira.greenbone.net/browse/DEVOPS-1093)

Fix: uses ruff check

---

pyproject.toml

Adjust the settings for ruff in the pyproject.toml,  Please update the following options in `pyproject.toml`:
'extend-select' -> 'lint.extend-select'
'ignore' -> 'lint.ignore'
'per-file-ignores' -> 'lint.per-file-ignores'}}
.. to prevent the printing of:
{{warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section.
[DEVOPS-1116](https://jira.greenbone.net/browse/DEVOPS-1116)

 Fix: Update outdated settings in pyproject.toml

---

tests/test_parser.py

Fix failing compression argument parser test for CI
It seems that with the runner and Python 3.12 the compression argument is uses as a string. Therefore don't include the actual passed argument when testing the error output.
https://github.com/greenbone/greenbone-feed-sync/actions/runs/12626669529/job/35241397170?pr=247

Fix failing compression argument parser test for CI

---

greenbone/feed/sync/config.py
greenbone/feed/sync/errors.py
tests/test_config.py
tests/test_parser.py

Drop the feed version from gvmd data directories by default
This change requires gvmd 25.0.0 and makes greenbone-feed-sync compatible with the 24.10 feed finally. The 24.10 feed is used by default with the current major release of greenbone-feed-sync.
Older feed versions for gvmd < 24.1.0 can be synced by setting the feed version. For example via the CLI argument `--feed-version 22.04`.
gvmd versions between 24.1.0 and 25.0.0 require to download the 24.10 feed into a 22.04 directory and are therefore considered broken.

Drop the feed version from gvmd data directories by default

---

README.md

Add a disclaimer for the feed version and used gvmd version
The current greenbone-feed-sync requires a specific gvmd version to work correctly out of the box.

Add a disclaimer for the feed version and used gvmd version

---

.github/workflows/changelog.yml
.github/workflows/release.yml
poetry.lock
pyproject.toml

Switch to git-cliff for generating the changelog of a release.
Better, improve and more flexible release changelogs.

Use git-cliff for release changelog generation

---

.github/workflows/push.yml

In order to fix workflow issue / DEVOPS-1534
Added permission pull-requests: write
Because the push job fails due to missing permissions for the workflow and the scout-command: cves that need to write a comment into the PR 
DEVOPS-1534
- [ -] Tests

CI-Workflow: add pull request write permission
